version: "3.8"

services:

  backend:
    build: ./backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - backend